name: Test and coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
      - name: Install Ruby dependencies
        run: bundle install
      - name: Run script
        run: |
          cd external-libraries
          git clone https://github.com/kward/shunit2.git
          cd ..
          cd Assignment-1
          bashcov run.sh
          cd tests
          bashcov run-test.sh
      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          file: coverage/coverage.xml